package com.fanjavaid.clean_architecture_flat_weather_app.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val lightColorPrimary = Color(0xFFAAAAAA)
val lightColorSecondary = Color(0xFFBBBBBB)
val lightColorTertiary = Color(0xFFCCCCCC)
val lightColorSurface = Color(0xFFEEEEEE)
val lightColorText = Color(0xFF333333)

val darkColorPrimary = Color(0xFF222222)
val darkColorSecondary = Color(0xFF444444)
val darkColorTertiary = Color(0xFF666666)
val darkColorSurface = Color(0xFF333333)
val darkColorText = Color(0xFFFFFFFF)

val seed = Color(0xFF6750A4)
val SuccessColor = Color(0xFF00B356)
val WarningColor = Color(0xFFFFAE2B)
val ErrorColor = Color(0xFFFF3526)
val WarningDarkerColor = Color(0xFFC77500)
val PurpleColor = Color(0xFFB353FF)
val DangerDarkerColor = Color(0xFF850046)
val light_SuccessColor = Color(0xFF006D32)
val light_onSuccessColor = Color(0xFFFFFFFF)
val light_SuccessColorContainer = Color(0xFF70FE96)
val light_onSuccessColorContainer = Color(0xFF00210A)
val dark_SuccessColor = Color(0xFF50E07D)
val dark_onSuccessColor = Color(0xFF003917)
val dark_SuccessColorContainer = Color(0xFF005224)
val dark_onSuccessColorContainer = Color(0xFF70FE96)
val light_WarningColor = Color(0xFF835500)
val light_onWarningColor = Color(0xFFFFFFFF)
val light_WarningColorContainer = Color(0xFFFFDDB4)
val light_onWarningColorContainer = Color(0xFF291800)
val dark_WarningColor = Color(0xFFFFB955)
val dark_onWarningColor = Color(0xFF452B00)
val dark_WarningColorContainer = Color(0xFF633F00)
val dark_onWarningColorContainer = Color(0xFFFFDDB4)
val light_ErrorColor = Color(0xFFC00003)
val light_onErrorColor = Color(0xFFFFFFFF)
val light_ErrorColorContainer = Color(0xFFFFDAD5)
val light_onErrorColorContainer = Color(0xFF410000)
val dark_ErrorColor = Color(0xFFFFB4A8)
val dark_onErrorColor = Color(0xFF690001)
val dark_ErrorColorContainer = Color(0xFF930001)
val dark_onErrorColorContainer = Color(0xFFFFDAD5)
val light_WarningDarkerColor = Color(0xFF8B5000)
val light_onWarningDarkerColor = Color(0xFFFFFFFF)
val light_WarningDarkerColorContainer = Color(0xFFFFDCBE)
val light_onWarningDarkerColorContainer = Color(0xFF2D1600)
val dark_WarningDarkerColor = Color(0xFFFFB871)
val dark_onWarningDarkerColor = Color(0xFF4A2800)
val dark_WarningDarkerColorContainer = Color(0xFF6A3C00)
val dark_onWarningDarkerColorContainer = Color(0xFFFFDCBE)
val light_PurpleColor = Color(0xFF8A20D6)
val light_onPurpleColor = Color(0xFFFFFFFF)
val light_PurpleColorContainer = Color(0xFFF2DAFF)
val light_onPurpleColorContainer = Color(0xFF2E004E)
val dark_PurpleColor = Color(0xFFE0B6FF)
val dark_onPurpleColor = Color(0xFF4C007C)
val dark_PurpleColorContainer = Color(0xFF6C00AE)
val dark_onPurpleColorContainer = Color(0xFFF2DAFF)
val light_DangerDarkerColor = Color(0xFFAC2963)
val light_onDangerDarkerColor = Color(0xFFFFFFFF)
val light_DangerDarkerColorContainer = Color(0xFFFFD9E2)
val light_onDangerDarkerColorContainer = Color(0xFF3E001E)
val dark_DangerDarkerColor = Color(0xFFFFB0C8)
val dark_onDangerDarkerColor = Color(0xFF650034)
val dark_DangerDarkerColorContainer = Color(0xFF8C094B)
val dark_onDangerDarkerColorContainer = Color(0xFFFFD9E2)

